# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tagsx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tagsx',
            new_name='tags',
        ),
    ]
